polygon_zkevm:
  rpc_url: "https://rpc.public.zkevm-test.net"
    
scroll_zkevm:
  rpc_url: "https://alpha-rpc.scroll.io/l2"

rollup_config:
  rollup_network:
    rpc_url: "ws://localhost:8546"
  batch_size: 2 # blocks


account_pk : "0x5dcc746cbd6c512cdd34cd1de8a9d0f038e6eb2ac9c4d12f2c22ab47de27fef4"